spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank Loans"
  contactDetails:
    name: "Shubham PROD"
    email: "shubham@prod"
  onCallSupport:
    - (222)222-1234
    - (222)222-5678