spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank Loans"
  contactDetails:
    name: "Shubham QA"
    email: "shubham@qa"
  onCallSupport:
    - (222)222-1234
    - (222)222-5678